create table categoria (
   id     number
      generated by default as identity
   primary key,
   nombre varchar2(50) not null
);

create table producto (
   id           number
      generated by default as identity
   primary key,
   nombre       varchar2(50) not null,
   precio       number(10,2) not null,
   stock        number not null,
   id_categoria number not null,
   foreign key ( id_categoria )
      references categoria ( id ),
   constraint chk_precio check ( precio >= 0 ),
   constraint chk_stock check ( stock >= 0 )
);

create table cliente (
   id           number
      generated by default as identity
   primary key,
   nombre       varchar2(50) not null,
   apellido     varchar2(50) not null,
   email        varchar2(100) not null,
   tipo_cliente varchar2(20) not null,
   constraint chk_tipo_cliente check ( tipo_cliente in ( 'natural',
                                                         'juridico' ) )
);

create table empleado (
   id            number
      generated by default as identity
   primary key,
   nombre        varchar2(50) not null,
   apellido      varchar2(50) not null,
   email         varchar2(100) not null,
   telefono      varchar2(15),
   direccion     varchar2(100),
   dni           varchar2(15) not null,
   fecha_ingreso date not null,
   salario       number(10,2) not null,
   constraint chk_salario check ( salario >= 0 )
);

create table venta (
   id          number
      generated by default as identity
   primary key,
   id_cliente  number not null,
   id_empleado number not null,
   fecha       date not null,
   estado      varchar2(20) not null,
   tipo_pago   varchar2(20) not null,
   foreign key ( id_cliente )
      references cliente ( id ),
   foreign key ( id_empleado )
      references empleado ( id ),
   constraint chk_estado
      check ( estado in ( 'pendiente',
                          'completada',
                          'cancelada' ) ),
   constraint chk_tipo_pago
      check ( tipo_pago in ( 'efectivo',
                             'yape',
                             'plin' ) )
);

create table detalle_venta (
   id          number
      generated by default as identity
   primary key,
   id_venta    number not null,
   id_producto number not null,
   cantidad    number not null,
   subtotal    number(10,2) not null,
   foreign key ( id_venta )
      references venta ( id ),
   foreign key ( id_producto )
      references producto ( id ),
   constraint chk_cantidad check ( cantidad > 0 ),
   constraint chk_subtotal check ( subtotal >= 0 )
);

create table boleta (
   id       number
      generated by default as identity
   primary key,
   id_venta number not null,
   fecha    date not null,
   dni      varchar2(15) not null,
   foreign key ( id_venta )
      references venta ( id )
);

create table factura (
   id           number
      generated by default as identity
   primary key,
   id_venta     number not null,
   fecha        date not null,
   ruc          varchar2(15) not null,
   razon_social varchar2(100) not null,
   foreign key ( id_venta )
      references venta ( id )
);